unit Testunt.front.enderecoDao;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, System.JSON, REST.Types, REST.Client, REST.Json, frm.dm.front,
  System.SysUtils, unt.front.endereco.dao, unt.endereco.dto;

type
  // Test methods for class TFEnderecoDados

  TestTFEnderecoDados = class(TTestCase)
  strict private
    FFEnderecoDados: TFEnderecoDados;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestLoad;
  end;

implementation

procedure TestTFEnderecoDados.SetUp;
begin
  FFEnderecoDados := TFEnderecoDados.Create;
end;

procedure TestTFEnderecoDados.TearDown;
begin
  FFEnderecoDados.Free;
  FFEnderecoDados := nil;
end;

procedure TestTFEnderecoDados.TestLoad;
var
  ReturnValue: TEnderecoDto;
  ACep: string;
begin
  ACep := '03606-010';
  ReturnValue := FFEnderecoDados.Load(ACep);
  CheckNotNull(ReturnValue, 'Erro da funcao load do dao');
end;

initialization
  RegisterTest(TestTFEnderecoDados.Suite);
end.

