unit Testunt.MenuPrin;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, unt.front.endereco.controller, Vcl.Dialogs, Winapi.Windows,
  Vcl.StdCtrls, System.SysUtils, System.Variants, Vcl.Graphics, Vcl.Mask,
  unt.MenuPrin.view, unt.endereco.dto, Winapi.Messages, Vcl.Controls, Vcl.Forms,
  System.Classes;

type
  // Test methods for class TfrmMenuPrin

  TestTfrmMenuPrin = class(TTestCase)
  strict private
    FfrmMenuPrin: TfrmMenuPrin;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestValidarCEP;
    procedure TestFormatarCep;
  end;

implementation

procedure TestTfrmMenuPrin.SetUp;
begin
  FfrmMenuPrin := TfrmMenuPrin.Create(nil);
end;

procedure TestTfrmMenuPrin.TearDown;
begin
  FfrmMenuPrin.Free;
  FfrmMenuPrin := nil;
end;

procedure TestTfrmMenuPrin.TestValidarCEP;
var
  ReturnValue: Boolean;
  ACep: string;
begin
  ACep := '03606-010';
  ReturnValue := FfrmMenuPrin.ValidarCEP(ACep);
  CheckTrue(ReturnValue, 'Erro na funcao ValidarCEP - responsavel por validar o cep');
end;

procedure TestTfrmMenuPrin.TestFormatarCep;
var
  ReturnValue: string;
  AValue: string;
begin
  AValue :=  '03606010';
  ReturnValue := FfrmMenuPrin.FormatarCep(AValue);
  CheckEqualsString('03606-010', ReturnValue, 'Erro na funcao TestFormatarCep - resposavel por formatar o cep');
end;

initialization
  RegisterTest(TestTfrmMenuPrin.Suite);
end.

