unit Testunt.endereco.daoo;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, unt.DM, unt.endereco.dao, REST.Types, REST.Client, REST.Json,
  System.SysUtils, System.JSON, unt.endereco.dto, unt.endereco.model;

type

  TestTEnderecoDao = class(TTestCase)
  strict private
    FEnderecoDao: TEnderecoDao;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestLoad;
  end;

implementation

procedure TestTEnderecoDao.SetUp;
begin
  FEnderecoDao := TEnderecoDao.Create;
end;

procedure TestTEnderecoDao.TearDown;
begin
  FEnderecoDao.Free;
  FEnderecoDao := nil;
end;

procedure TestTEnderecoDao.TestLoad;
var
  ReturnValue: TEnderecoDto;
  ACep: string;
begin
  ACep := '03606-010';
  ReturnValue := FEnderecoDao.Load(ACep);
  CheckNotNull(ReturnValue, 'Erro ao carregar o load do dao.');
end;

initialization
  RegisterTest(TestTEnderecoDao.Suite);
end.

