unit Testunt.endreco.controller;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, unt.endreco.controller, unt.endereco.dto, unt.endereco.dao;

type
  // Test methods for class TEnderecoController

  TestTEnderecoController = class(TTestCase)
  strict private
    FEnderecoController: TEnderecoController;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestLoad;
  end;

implementation

procedure TestTEnderecoController.SetUp;
begin
  FEnderecoController := TEnderecoController.Create;
end;

procedure TestTEnderecoController.TearDown;
begin
  FEnderecoController.Free;
  FEnderecoController := nil;
end;

procedure TestTEnderecoController.TestLoad;
var
  ReturnValue: TEnderecoDto;
  ACep: string;
begin
  ACep := '03606-010';
  ReturnValue := FEnderecoController.Load(ACep);
  CheckNotNull(ReturnValue, 'Erro ao testar a funcao load do controller.');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTEnderecoController.Suite);
end.

